//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schroeter.PhotoTagStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Headlines {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Headlines"]));
            }
            set {
                this["Headlines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Captions {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Captions"]));
            }
            set {
                this["Captions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Objectnames {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Objectnames"]));
            }
            set {
                this["Objectnames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Writers {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Writers"]));
            }
            set {
                this["Writers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Authors {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Authors"]));
            }
            set {
                this["Authors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Copyrights {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Copyrights"]));
            }
            set {
                this["Copyrights"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Keywords {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Keywords"]));
            }
            set {
                this["Keywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList Contacts {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["Contacts"]));
            }
            set {
                this["Contacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.LocationList Locations {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.LocationList)(this["Locations"]));
            }
            set {
                this["Locations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayIPTCTagsWithFlickrNames {
            get {
                return ((bool)(this["DisplayIPTCTagsWithFlickrNames"]));
            }
            set {
                this["DisplayIPTCTagsWithFlickrNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.GroupedTagList GroupedKeywords {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.GroupedTagList)(this["GroupedKeywords"]));
            }
            set {
                this["GroupedKeywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GuiShowPreview {
            get {
                return ((bool)(this["GuiShowPreview"]));
            }
            set {
                this["GuiShowPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GuiShowDirectoryTree {
            get {
                return ((bool)(this["GuiShowDirectoryTree"]));
            }
            set {
                this["GuiShowDirectoryTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RotatePreview {
            get {
                return ((bool)(this["RotatePreview"]));
            }
            set {
                this["RotatePreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan GPSTimeOffset {
            get {
                return ((global::System.TimeSpan)(this["GPSTimeOffset"]));
            }
            set {
                this["GPSTimeOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KmzHeading {
            get {
                return ((int)(this["KmzHeading"]));
            }
            set {
                this["KmzHeading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KmzTilt {
            get {
                return ((int)(this["KmzTilt"]));
            }
            set {
                this["KmzTilt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int KmzRange {
            get {
                return ((int)(this["KmzRange"]));
            }
            set {
                this["KmzRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KmzOpenFile {
            get {
                return ((bool)(this["KmzOpenFile"]));
            }
            set {
                this["KmzOpenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int KmzPictureSize {
            get {
                return ((int)(this["KmzPictureSize"]));
            }
            set {
                this["KmzPictureSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadThumbnailsInBackground {
            get {
                return ((bool)(this["LoadThumbnailsInBackground"]));
            }
            set {
                this["LoadThumbnailsInBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWorkingDirectory {
            get {
                return ((string)(this["LastWorkingDirectory"]));
            }
            set {
                this["LastWorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoToNextPicture {
            get {
                return ((bool)(this["GoToNextPicture"]));
            }
            set {
                this["GoToNextPicture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewSettingFile {
            get {
                return ((bool)(this["NewSettingFile"]));
            }
            set {
                this["NewSettingFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.PresetStore PresetModels {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.PresetStore)(this["PresetModels"]));
            }
            set {
                this["PresetModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList FilenameFormats {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["FilenameFormats"]));
            }
            set {
                this["FilenameFormats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.TagList DirectorynameFormats {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.TagList)(this["DirectorynameFormats"]));
            }
            set {
                this["DirectorynameFormats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MacroDirectory {
            get {
                return ((string)(this["MacroDirectory"]));
            }
            set {
                this["MacroDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Schroeter.PhotoTagStudio.Data.RecentList MacroRecentFiles {
            get {
                return ((global::Schroeter.PhotoTagStudio.Data.RecentList)(this["MacroRecentFiles"]));
            }
            set {
                this["MacroRecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenameUseSubdirectories {
            get {
                return ((bool)(this["RenameUseSubdirectories"]));
            }
            set {
                this["RenameUseSubdirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MacroUseSubdirectories {
            get {
                return ((bool)(this["MacroUseSubdirectories"]));
            }
            set {
                this["MacroUseSubdirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int KmzLineWidth {
            get {
                return ((int)(this["KmzLineWidth"]));
            }
            set {
                this["KmzLineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color KmzLineColor {
            get {
                return ((global::System.Drawing.Color)(this["KmzLineColor"]));
            }
            set {
                this["KmzLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IPTC</string>
  <string>EXIF</string>
  <string>EXIF Dates</string>
  <string>Rename</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VisibleTabs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VisibleTabs"]));
            }
            set {
                this["VisibleTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CollapseIptcKeywordGroupsOnStartup {
            get {
                return ((bool)(this["CollapseIptcKeywordGroupsOnStartup"]));
            }
            set {
                this["CollapseIptcKeywordGroupsOnStartup"] = value;
            }
        }
    }
}
